from tkinter import*
import tkinter as tk
from tkinter.ttk import* 
from tkinter import messagebox

tk=Tk()
tk.geometry("1500x1500")
tk.configure(background="#1CD1CE")
c=Canvas(tk,width=1500,height=1500)
c.place(x=0,y=0)
img=PhotoImage(file='path\\cycle.png')
c.create_image(0,0,anchor=NW,image=img)

def bar():
     t2=Toplevel(tk)
     t2.configure(background="#E80770")
     t2.geometry("1500x1500")
     #t2.configure(background="FD9196")
     c=Canvas(t2,width=350,height=300,background="black")
     c.place(x=0,y=100)
     img=PhotoImage(file='path\\bag1.png')
     c.create_image(0,0,anchor=NW,image=img)
     def first():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)

      #bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="offred waterproof fabric",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text=" dark_blue ,red",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 500 ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)
      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
         
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=first)
     b.place(x=150,y=380) 
     c1=Canvas(t2,width=350,height=300,background="black")
     c1.place(x=550,y=100)
     img1=PhotoImage(file='path\\bag2.png')
     c1.create_image(0,0,anchor=NW,image=img1)
     def second():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)
      # bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="offred waterproof fabric",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text=" Baby_pink,black",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 1000 ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)
      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
         
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=second)
     b.place(x=700,y=380) 
     c2=Canvas(t2,width=350,height=300,background="black")
     c2.place(x=1100,y=100)
     img2=PhotoImage(file='path\\bag4.png')
     c2.create_image(0,0,anchor=NW,image=img2)
     def third():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)
     # bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="offred waterproof fabric",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text=" Dark_blue,kesari",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 1000 ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)
      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=first)
     b.place(x=150,y=380)
     b=Button(t2,text="buy",command=third)
     b.place(x=1250,y=380) 
     c3=Canvas(t2,width=350,height=300,background="black")
     c3.place(x=0,y=450)
     img3=PhotoImage(file='path\\bag4.png')
     c3.create_image(0,0,anchor=NW,image=img3)
     def fourth():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)
      # bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="offred waterproof fabric",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text="Faint_blue,kesari",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 1000 ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)

      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=first)
     b.place(x=150,y=380)
     b=Button(t2,text="buy",command=fourth)
     b.place(x=150,y=750) 
     c4=Canvas(t2,width=350,height=300,background="black")
     c4.place(x=550,y=450)
     img4=PhotoImage(file='path\\bag5.png')
     c4.create_image(0,0,anchor=NW,image=img4)
     def fifth():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)
      # bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="silk",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text=" Sky_blue",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 500 ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)

      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=first)
     b.place(x=150,y=380)
     b=Button(t2,text="buy",command=fifth)
     b.place(x=700,y=750) 
     c5=Canvas(t2,width=350,height=300,background="black")
     c5.place(x=1100,y=450)
     img5=PhotoImage(file='path\\bag6.png')
     c5.create_image(0,0,anchor=NW,image=img5)
     def sixth():
      tp1=Toplevel(t2)
      tp1.configure(background="#DD1D0D")
      tp1.geometry("1500x1500")
      l=Label(tp1,text="Customer Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=200,y=0)
      l=Label(tp1,text=" Customer Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=100,y=150)
      e1=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e1.place(x=400,y=150)
      l=Label(tp1,text=" State",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=220)
      e3=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e3.place(x=400,y=220)
      l=Label(tp1,text=" City",font=("vijaya",22),width=20,foreground="white",background="indigo")
      l.place(x=100,y=290)
      e4=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e4.place(x=400,y=290)
      l=Label(tp1,text="address ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=360)
      e5=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e5.place(x=400,y=360)
      l=Label(tp1,text="mobail no ",font=("vijaya",22),foreground="white",background="indigo",width=20)
      l.place(x=100,y=430)
      e6=Entry(tp1,font=("Arial",25),foreground="red",width=15)
      e6.place(x=400,y=430)
      # bag details
      l=Label(tp1,text="Bag Details",font=("vijaya",50),foreground="yellow",background="#DD1D0D")
      l.place(x=900,y=0)
      l=Label(tp1,text=" Company Name ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=150)
      l=Label(tp1,text=" hashtag ",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=150)
      l=Label(tp1,text="Fabric",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=220)
      l=Label(tp1,text="offred waterproof fabric",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=220)
      l=Label(tp1,text=" Colour ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=290)
      l=Label(tp1,text="Faint_pink",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=290)
      l=Label(tp1,text=" Prize ",font=("vijaya",25),width=20,foreground="white",background="indigo")
      l.place(x=800,y=360)
      l=Label(tp1,text=" 500",font=("vijaya",25),width=20,foreground="black",background="white")
      l.place(x=1100,y=360)
      def buyc():
        msg=messagebox.showinfo("information","you are order is confirm it deliver to you in 2-3 days")
      b3=Button(tp1,text="  buy ",width=10,command=buyc)
      b3.place(x=400,y=650)
      def cancel():
       tp1.destroy()  
      b3=Button(tp1,text="cancle",width=15,command=cancel)
      b3.place(x=900,y=650)  
      tp1.mainloop()
     b=Button(t2,text="buy",command=first)
     b.place(x=150,y=380)
     b=Button(t2,text="buy",command=sixth)
     b.place(x=1250,y=750)
     l=Label(t2,text=" Company ",font=("vijaya",40),foreground="#FEF014",background="crimson")
     l.place(x=600,y=0)
     t2.mainloop()
Button(tk,text="welcome",command=bar).place(x=650,y=450)
mainloop()

 



     

